### ISSUE TITLE
а нахуя нашего бота сливать

### ISSUE THREAD

**Issue by frrrrrrqqfnlllflwe** [DLeaksss/AntiCrash-Bots#1]
1

**Comment by thelittlepony** [comment]
Действительно, ваш бот тоже форк +Плохо работает
Могли бы хотя бы премиум убрать, и написать что это форк?

**Comment by win-home** [comment]
Почему он форк?

**Comment by win-home** [comment]
Ты про FinonBot?

**Comment by thelittlepony** [comment]
finonbot повторяю, плохо написан +украден код
RX-Protect который от вас с xiodazeroм по инфе от кое кого, форк Hi-Protect

**Comment by win-home** [comment]
расскажешь ещё
